layout_spectrum: 0.8878583
typography_spectrum: 0.6096122
color:
  lightness: 0.08853288
  brandStrength: 0.8693086
  saturation: 0.4645869
  rhythmicContrast: 0.9468803
  brandColors:
    - '#242325'
    - '#FFFEFF'
    - '#787777'
    - '#CDBEBE'
    - '#30545B'
name: Rasha
