name: Rasha
favicon: null
layout_spectrum: 0.2507
typography_spectrum: 0.6096122
title: Gatta - all crazy about bikes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6fff8'
    - '#0f0e13'
    - '#694644'
    - '#aa664f'
    - '#eaa180'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
