name: Rasha
favicon: null
layout_spectrum: 0.8878583
typography_spectrum: 0.6096122
title: Gatta - all crazy about bikes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242325'
    - '#FFFEFF'
    - '#787777'
    - '#CDBEBE'
    - '#30545B'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.9468803
purpose: []
