name: Rasha
favicon: null
layout_spectrum: 0.8878583
typography_spectrum: 0.6096122
title: Gatta - all crazy about bikes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040402'
    - '#706bad'
    - '#fcfecc'
    - '#caa3cf'
    - '#d4595b'
  brandStrength: 1
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
